Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,11 +25,6 @@ jobs:
         choco install mingw --force -y
         echo "C:\ProgramData\mingw64\mingw64\bin" >> %GITHUB_PATH%
 
-    - name: Install DirectX SDK
-      shell: cmd
-      run: |
-        choco install directx-sdk -y
-
     - name: Install vcpkg
       shell: cmd
       run: |
@@ -39,7 +34,7 @@ jobs:
     - name: Install dependencies via vcpkg
       shell: cmd
       run: |
-        .\vcpkg\vcpkg install imgui[dx11,win32]:x64-mingw-static minhook:x64-mingw-static nlohmann-json:x64-mingw-static zlib:x64-mingw-static --recurse --clean-after-build
+        .\vcpkg\vcpkg install imgui:x64-mingw-static minhook:x64-mingw-static nlohmann-json:x64-mingw-static --recurse --clean-after-build
         .\vcpkg\vcpkg integrate install
 
     - name: Install CMake
@@ -59,11 +54,12 @@ jobs:
         dir
         dir DirectXSample
         dir DirectXSample\CMakeLists.txt 2> nul || echo "CMakeLists.txt not found in DirectXSample"
+        dir DirectXSample\src\RustAlkadCheat2588.cpp 2> nul || echo "RustAlkadCheat2588.cpp not found"
 
     - name: Configure CMake
       shell: cmd
       run: |
-        cmake -S DirectXSample -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
+        cmake -S DirectXSample -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -CMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
 
     - name: Build
       shell: cmd
